env_parameters:
  env_name: "PegInHole"
  robots: ["Indy7"]
  controller: "config/controller/indy7_absolute_pose.json"
  prehensile: False
  camera_names: ["frontview", "agentview", "robot0_eye_in_hand"]
  camera_heights: 256
  camera_widths: 256
  camera_depths: False
  control_freq: 20
  seed: 0
  max_iter: 1000

task_parameters:
  num_episodes : 50
  episode_len: 600
  dataset_dir: "data_collection/datasets/pih"
  ckpt_dir: "ckpt/ACT/pih/"
  camera_names: ["agentview", "robot0_eye_in_hand"]